[default]
FLASK_DEBUG="TRUE"

[test]
host="localhost" 
port="3306"
database="snippets_test_a"
user="snippets_test_admin"

[testa]
host="192.168.0.42" 
port="3306"
database="snippets_test_a"
user="snippets_test_admin"

[production]
host="192.168.0.42"
port="3306"
database="snippets_production_a"
user="snippets_prod_admin"
