[default]
SECRET_KEY = "your-secret-key"
FLASK_DEBUG="TRUE"


[development]
mysql = {host="localhost", port=3306, database="snippetsdb_testa", auth={user="snippets_test", passwd="15485099a433658c4701487c66caa3747c831f3440d435b6"}}


[personal]
mysql = {host="192.168.0.42", port=3306, database="personal_snippetsdb", auth={user="adam", passwd="savagge23.3"}}



[pi]
mysql = {host="192.168.0.42", port=3306, database="snippetsdb_testa", auth={user="root", passwd="Suffocate7-Eloquent-Confined"}}