[default]
FLASK_DEBUG="TRUE"
host="localhost" 
port="3306"
database="snippetsdb_testa"
user="snippets_test"

[local_test]
host="localhost" 
port="3306"
database="snippetsdb_testa"
user="snippets_test"

[personal]
host="192.168.0.42"
port="3306"
database="personal_snippetsdb"
user="adam"

[pi]
host="192.168.0.42"
port="3306"
database="testa_snippetsdb"
user="root"