[default]
SECRET_KEY = "your-secret-key"
FLASK_DEBUG = true

[development]
mysql = {host="localhost", port=3306, database="snippetsdb_testa", auth={user="snippets_test", passwd="15485099a433658c4701487c66caa3747c831f3440d435b6"}}

[personal]
mysql = {host="192.168.0.42", port=3306, database="personal_snippetsdb", user="adam", auth={user="adam", passwd="savagge23.2"}}
